export const languages = [
    'JavaScript', 
    'TypeScript', 
    'Python', 
    'Java', 
    'C#',
    'Go',
    "Ruby",
    'PHP',
    'Rust',
    'Kotlin',
    'Swift',
    'C',
    'C++',
]

export const databases = [
    'PostgreSQL',
    'MySQL',
    'Microsoft SQL Server',
    'MongoDB',
    'Redis',
    'Cassandra',
    'Neo4j',
    'InfluxDB',
    'FireBase',
    'AWS DynamoDB',
    'SQLite',
    'TypeORM',
]

export const frameworks = [
    'React',
    'Angular',
    'Vue.js',
    'Svelte',
    'Express',
    'NestJS',
    'Django',
    'Flask',
    'FastAPI',
    'Spring Boot',
    '.NET',
    'Flutter',
    'React Native',
    'Jest',
    'Cypress',
    'Selenium',
    'Unreal Engine',
    'Keras',
    'Scikit Learn',
    'Pandas',
    'TensorFlow',
    'PyTorch',
    'PhalconPHP',
    '1C',
    'Node.js',
    'Next.js',
    'Tailwind',
    'Bootstrap',
    'Mocha',
]

export const devops = [
    'Docker',
    'Kubernetes',
    'Jenkins',
    'GitLab CI/CD',
    'GitHub Actions',
    'Terraform',
    'Ansible',
    'Prometheus',
    'Grafana',
    'ELK Stack',
    'AWS',
    'Azure',
    'Google Cloud',
    'Elasticsearch',
]